# Generated by Django 3.2.16 on 2022-12-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_orders_details_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_details',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders_details',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders_details',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
